POST http://localhost:3000/passengers HTTP/1.1
content-type: application/json

{"name":"mongodb 2", "location":"kuzguncuk"}

###

GET http://localhost:3000/passengers/65c8e3d870dad35ee035663f HTTP/1.1

###
DELETE http://localhost:3000/passengers/65c8e3d870dad35ee035663f HTTP/1.1