POST http://localhost:3000/passengers HTTP/1.1
content-type: application/json

{"name":"4", "age":18, "location":"kuzguncuk"}

###

GET http://localhost:3000/passengers/65c8e74744d8ec0be6496913 HTTP/1.1

###
DELETE http://localhost:3000/passengers/65c8e3d870dad35ee035663f HTTP/1.1


###

PATCH http://localhost:3000/passengers/65c8e74744d8ec0be6496913 HTTP/1.1
content-type: application/json

{"name": "hilal"}

###
POST http://localhost:3000/drivers HTTP/1.1
content-type: application/json

{"name":"hilal young driver", "age":21, "location":"Levent"}
###
DELETE http://localhost:3000/drivers/65ca0b88fc4cc047dc4a006e HTTP/1.1


###

GET http://localhost:3000/drivers/65ca5821fc586669549c1cc8 HTTP/1.1



###

POST http://localhost:3000/passengers/65c8e74744d8ec0be6496913/bookings HTTP/1.1
content-type: application/json

{"driverId": "65ca5821fc586669549c1cc8",
 "origin": "Eminonu", 
 "destination": "Bebek"}


###


PATCH http://localhost:3000/drivers/65ca5821fc586669549c1cc8 HTTP/1.1
content-type: application/json

{"name": "whyy"}

###
POST http://localhost:3000/passengers/65c8e74744d8ec0be6496913/bookings HTTP/1.1
content-type: application/json

{"driverId": "65cb9a6e00133f76c0a9a534", "origin": "Kabatas", "destination": "Pendik"}



###

GET http://localhost:3000/bookings HTTP/1.1

